config/routes.rb
Rails.application.routes.draw do
  admin_domain = Cubecomp::Application.config.admin_domain

  constraints HostRouteConstraint.new(admin_domain) do
    scope module: 'admin', as: 'admin', path: (admin_domain ? "/" : "/admin"), format: false do
      root action: 'index'

      get 'login', to: 'sessions#new'
      post 'login', to: 'sessions#create'
      delete 'logout', to: 'sessions#destroy'

      resources :users, except: [:show]

      get :help, to: "help#index"

      theme_files_resources = lambda do
        member do
          get :show_image
        end

        collection do
          get :new_image
          post :create_image

          get :import_files, action: 'import_files_form'
          post :import_files
        end
      end

      resources :themes do
        resources :theme_files, except: [:show], &theme_files_resources
      end

      resources :competitions, except: [:show] do
        resources :dashboard, only: [:index]

        resources :competitors, except: [:show] do
          collection do
            get :checklist
            get :nametags
            get :email_addresses
            get :csv
            get :csv_download_active
          end

          member do
            patch :confirm
            patch :cancel
            patch :mark_as_paid
          end

          member do
            get 'email(/:activate)', to: 'competitor_email#new', as: 'new_email'
            post 'email', to: 'competitor_email#create', as: 'create_email'

            get 'email/render(.:format)(/:email_template_id)',
              to: 'competitor_email#render_template',
              as: 'render_email',
              constraints: { format: 'json' }
          end
        end

        resources :event_registrations, only: [] do
          collection do
            get :waiting
            patch :remove_all_waiting
          end
        end

        resources :events, except: [:show] do
          collection do
            get 'print/(:day_id)', action: 'print', as: "print"
            delete 'destroy_day/:day_id', action: 'destroy_day', as: 'destroy_day'

            get :import_day, action: 'import_day_form'
            post :import_day
          end

          resources :event_registrations, only: [:index, :destroy] do
            member do
              patch :update_waiting
            end
          end
        end

        resources :news, except: [:show]
        resources :theme_files, except: [:show], &theme_files_resources

        resources :email_templates, except: [:show] do
          collection do
            get :import_templates, action: 'import_templates_form'
            post :import_templates
          end
        end
      end
    end
  end

  constraints HostRouteConstraint.new(admin_domain, negate: true) do
    scope '/wca' do
      get '/autocomplete/(:q.:format)',
        to: 'wca#autocomplete',
        as: 'wca_autocomplete',
        constraints: { format: 'json' }
    end

    get '/', to: "front_page#index"

    scope '/:competition_handle' do
      post '/:locale/registration',
        to: 'competition_area/competitors#create',
        as: 'competition_area_competitor_create'

      get '/(:locale/(:theme_file))',
        to: 'competition_area#render_theme_file',
        as: 'competition_area'
    end
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :competition
  validates :competition, presence: true

  STATES = {
    'open_for_registration' => 'Open for registration',
    'open_with_waiting_list' => 'Waiting list',
    'registration_closed' => 'Closed (not open anymore)',
    'not_for_registration' => 'Not for registration'
  }.freeze

  belongs_to :day
  validates :day, presence: true

  has_many :registrations, class_name: 'EventRegistration', dependent: :destroy

  has_many :competitors, through: :registrations

  validates :name, presence: true

  validates :handle, presence: true, if: :for_registration?
  validates :handle,
    uniqueness: {
      scope: :competition_id,
      message: lambda do |_, e|
        "#{e[:value]} has already been used by another event of this competition that is also for registration"
      end,
      case_sensitive: true
    },
    allow_nil: true,
    allow_blank: true,
    if: :for_registration?

  validates :start_time, presence: true
  validates :length_in_minutes, numericality: {
    only_integer: true,
    greater_than: 0
  }, allow_nil: true, allow_blank: true

  validates :max_number_of_registrations, numericality: {
    only_integer: true,
    greater_than: 0
  }, allow_nil: true, allow_blank: true

  validates :state, presence: true
  validates :state, inclusion: { in: Event::STATES.keys }, allow_nil: true, allow_blank: true

  auto_strip_attributes :name, :handle, :timelimit, :format, :round, :proceed

  scope :for_competitors_table, ->{ where.not(state: 'not_for_registration') }
  scope :wca, ->{ where(handle: WCA_EVENTS.map{ |event| [ event[:handle], event[:wca_handle] ] }.flatten.compact.uniq) }

  scope :for_registration, ->{ where.not(state: 'not_for_registration') }

  scope :with_max_number_of_registrations, lambda {
    select('events.*, COUNT(DISTINCT(competitors.id)) AS number_of_confirmed_registrations')
      .where('max_number_of_registrations IS NOT NULL')
      .where('max_number_of_registrations >= 0')
      .joins(:competitors)
      .where('competitors.state' => 'confirmed')
      .joins(:day)
      .order('days.date ASC')
      .group('events.id')
  }

  validate :validate_cant_be_not_for_registration_if_registrations_exist

  def for_registration?
    state != 'not_for_registration'
  end

  def wca_handle
    return unless wca_handle_index
    WCA_EVENTS[wca_handle_index][:wca_handle]
  end

  def wca_handle_index
    @wca_handle_index ||= begin
      index = WCA_EVENTS.find_index{ |wca_event| handle == wca_event[:handle] }
      index ||= WCA_EVENTS.find_index{ |wca_event| handle == wca_event[:wca_handle] }
      index
    end
  end

  def registrations?
    !registrations.reject(&:marked_for_destruction?).empty?
  end

  def end_time
    return unless length_in_minutes
    start_time + length_in_minutes.minutes
  end

  private

  def validate_cant_be_not_for_registration_if_registrations_exist
    return if for_registration?
    return unless registrations?
    errors.add(:state, "state can't be \"#{STATES['not_for_registration']}\" if event already has registrations")
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < AdminController
  before_action :set_event, only: [:edit, :update, :destroy]

  PERMITTED_PARAMS = [
    :name,
    :handle,

    :day_id,
    :start_time,
    :length_in_minutes,

    :round,
    :timelimit,
    :format,
    :proceed,
    :max_number_of_registrations,
    :state
  ].freeze

  def index
    @events = current_competition.events.includes(:registrations => :competitor)
    @days = current_competition.days.with_events
  end

  def print
    day_id = params[:day_id].presence || current_competition.days.first.id
    @day = current_competition.days.find(day_id)
    render 'liquid/_schedule', layout: 'admin/schedule', locals: { day: @day }
  end

  def import_day_form
    format_date = ->(date) { I18n.l(date, format: :schedule) }

    @from_options = from_options_for_import_day_form
      .map{ |name, day_id, date, count| [ "#{name}, #{format_date.call(date)} (#{count} events)", day_id ] }

    @to_options = current_competition.days.map do |day|
      [ "#{current_competition.name}, #{format_date.call(day.date)}", day.id ]
    end
  end

  def import_day
    @day_to = current_competition.days.find_by!(id: params[:to_day_id])
    @day_from = Day.find_by!(id: params[:from_day_id])

    @day_to.transaction do
      DayEventsImportService.new(@day_from, @day_to).replace!
    end

    redirect_to admin_competition_events_path(current_competition), notice: 'Events successfully imported.'

  rescue ActiveRecord::RecordInvalid => e
    redirect_to admin_competition_events_path(current_competition),
      flash: { error: e.record.errors.full_messages.join(', ') }
  end

  def new
    @event = current_competition.events.new
  end

  def edit
  end

  def create
    @event = current_competition.events.new(event_params)

    if @event.save
      redirect_to admin_competition_events_path(current_competition),
        notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  def update
    if @event.update(event_params)
      redirect_to admin_competition_events_path(current_competition),
        notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to admin_competition_events_url(current_competition),
      notice: 'Event was successfully deleted.'
  end

  def destroy_day
    @events = current_competition.events.where(day_id: params[:day_id])
    @events.destroy_all
    redirect_to admin_competition_events_url(current_competition),
      notice: 'Events for the day were successfully deleted.'
  end

  private

  def set_event
    @event = current_competition.events.find(params[:id])
  end

  def event_params
    params.require(:event).permit(PERMITTED_PARAMS)
  end

  def from_options_for_import_day_form
    Competition
      .joins(days: :events)
      .where.not('competitions.id' => current_competition.id)
      .group('competitions.name, days.date')
      .order('competitions.name, days.date')
      .pluck(Arel.sql('competitions.name, days.id, days.date, COUNT(events.id)'))
  end
end

app/views/admin/events/_form.html.erb
<%= form_for([:admin, current_competition, @event]) do |f| %>
  <%= render 'form_errors', object: @event, label: 'event' %>

  <%= form_section 'Standard WCA Events' do %>
    <table class='form-table'>
      <tr>
        <td>
          <select id="standard-wca-events">
            <% WCA_EVENTS.each_with_index do |event, index| %>
              <option value="<%= index %>"><%= event[:name] %> (<%= event[:format] %>)</option>
            <% end %>
          </select>
        </td>
        <td>
          <%= link_to 'Load', {}, { id: 'standard-wca-event-load-button', class: 'button' } %>
          <%= javascript_tag do %>
            var wca_events = <%= raw WCA_EVENTS.to_json %>
            $("a#standard-wca-event-load-button").click(function(event) {
              index = parseInt($("select#standard-wca-events").val());
              wca_event = wca_events[index];
              $("#event_name").val(wca_event["name"]);
              $("#event_format").val(wca_event["format"]);
              $("#event_handle").val(wca_event["handle"]);

              event.preventDefault();
            });
          <% end %>
        </td>
      </tr>
    </table>
  <% end %>

  <%= form_section 'Name' do %>
    <table class="form-table">
      <tr>
        <td><%= f.label :name, 'Name:' %></td>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <td><%= f.label :handle, 'Handle:' %></td>
        <td>
          <%= f.text_field :handle %>
          <%= help_tooltip %q{
            If this is an official WCA event, you should not change this value but use
            the suggested default value (from the "Load" button above).
          } %>
        </td>
      </tr>
    </table>
  <% end %>

  <%= form_section 'Time' do %>
    <table class="form-table">
      <tr>
        <td><%= f.label :day, 'Day:' %></td>
        <td><%= f.select :day_id, current_competition.days.order(:date).map{ |day| [ l(day.date, format: :schedule), day.id ] } %></td>
      </tr>
      <tr>
        <td><%= f.label :start_time, "Start:" %></td>
        <td><%= f.time_select :start_time, { minute_step: 5 }, { class: 'time-select' } %></td>
      </tr>
      <tr>
        <td><%= f.label :length_in_minutes, "Length:" %></td>
        <td><%= f.select :length_in_minutes, [["", nil]] + options_for_minutes %></td>
      </tr>
    </table>
  <% end %>

  <%= form_section 'Options' do %>
    <table class="form-table">
      <tr>
        <td><%= f.label :round, 'Round:' %></td>
        <td><%= f.text_field :round %></td>
      </tr>
      <tr>
        <td><%= f.label :timelimit, 'Time limit:' %></td>
        <td><%= f.text_field :timelimit %></td>
      </tr>
      <tr>
        <td><%= f.label :format, 'Format:' %></td>
        <td><%= f.text_field :format %></td>
      </tr>
      <tr>
        <td><%= f.label :proceed, 'Proceed:' %></td>
        <td><%= f.text_field :proceed %></td>
      </tr>
      <tr>
        <td><%= f.label :max_number_of_registrations, 'Max. registrations:' %></td>
        <td>
          <%= f.select :max_number_of_registrations, [["Unlimited", nil]] + (5..500).step(5).to_a %>
          <%= help_tooltip %q{
            This field does not influence the registration status of events.
            If the maximum number is reached, people will still be able to register.
            This is purely informative: This number will appear in the schedule and
            in overviews/statistics.
          } %>
        </td>
      </tr>
      <tr>
        <td><%= f.label :state, 'State:' %></td>
        <td>
          <% options = @event.registrations? ? { disabled: 'not_for_registration' } : {} %>
          <% options[:selected] = @event.state %>
          <%= f.select :state, options_for_select(Event::STATES.to_a.map(&:reverse), options) %>
          <%= help_tooltip %q{
            <p>
              Use the status <b>Not for registration</b> for events for which people should
              never be able to register for, like final rounds, lunch breaks, winners' ceremonies,
              etc.
            </p>
            <p>
              If an event has status <b>waiting list</b>, people will still be able to register
              for that event, but they will have a special flag set, which marks them as "waiting"
              (and you can compare who registered first for an waiting list event).
            </p>
            <p>
              If an event is <b>closed</b>, people will not be able to register anymore. Admins
              however will still be able to register people, regardless of the events status.
            </p>
          } %>
        </td>
      </tr>
    </table>
  <% end %>

  <%= submit_button(f) %>
  <%= back_button admin_competition_events_path(current_competition) %>
<% end %>

app/views/admin/events/_table.html.erb
<h2>
  <%= I18n.l(day.date, format: :schedule) %>
  <%=
    delete_button(
      destroy_day_admin_competition_events_path(current_competition, day.id),
      method: :delete,
      data: { confirm: 'Are you sure?' }
    )
  %>
</h2>

<table class='default-table events'>
  <thead>
    <tr>
      <th>Start</th>
      <th>End</th>
      <th>Event</th>
      <th>Round</th>
      <th>Time-limit</th>
      <th>Format</th>
      <th>Confirmed registrations</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @events.select{ |event| event.day_id == day.id }.sort_by(&:start_time).each do |event| %>
      <tr class="<%= "not_for_registration" unless event.for_registration? %>">
        <td><%= event.start_time.strftime("%H:%M") %></td>
        <td><%= event.end_time.try!(:strftime, "%H:%M") %></td>
        <td><%= event.name %></td>
        <td><%= event.round %></td>
        <td><%= event.timelimit %></td>
        <td>
          <%= event.format %>
          <% if event.proceed.present? %>
            <br/>
            <small><%= event.proceed %> proceed</small>
          <% end %>
        </td>
        <td>
          <% if event.for_registration? %>
            <% confirmed = event.registrations.select{ |r| r.competitor.confirmed? } %>
            <%= confirmed.size %> (<%= confirmed.select(&:waiting).size %> waiting)
          <% end %>
        </td>
        <td>
          <%= edit_button(edit_admin_competition_event_path(current_competition, event)) %>
          <%=
            delete_button(
              admin_competition_event_path(current_competition, event),
              method: :delete,
              data: { confirm: 'Are you sure?' }
            )
          %>
          <% if event.for_registration? %>
            <%= show_button('Show registrations', admin_competition_event_event_registrations_path(current_competition, event)) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/events/edit.html.erb
<% page_title @event.name %>

<%= render 'form' %>

app/views/admin/events/import_day_form.html.erb
<% page_title 'Import day' %>

<% if (@from_options.size + @to_options.size) > 0 %>
  <p><b>Note:</b> Importing a day from another competition will delete all of the existing events for the day of this competition.</p>

  <%= form_tag(import_day_admin_competition_events_path) do %>
    <table class='form-table'>
      <tr>
        <td>Import from:</td>
        <td><%= select_tag 'from_day_id', options_for_select(@from_options), class: 'inline' %></td>
      </tr>
      <tr>
        <td>Save to:</td>
        <td><%= select_tag 'to_day_id', options_for_select(@to_options), class: 'inline' %></td>
      </tr>
      <tr>
        <td colspan="2" style="text-align: right">
          <%= submit_button(nil, "Import", data: { confirm: 'Are you sure? This will delete your existing events for this day!' }) %>
          <%= back_button(admin_competition_events_path) %>
        </td>
      </tr>
    </table>
  <% end %>
<% else %>
  There are no themes available to load right now.
<% end %>

app/views/admin/events/index.html.erb
<% page_title 'Events' %>

<p>
  <%= link_to 'Import day from other competition', import_day_admin_competition_events_path(current_competition) %><br/>
  <%= link_to 'New event', new_admin_competition_event_path %><br/>
  <%= link_to 'Waiting list overview', waiting_admin_competition_event_registrations_path(current_competition) %><br/>
  <% if @days.any? %>
    Printable schedules:
    <% @days.each do |day| %>
      <%= link_to l(day.date, format: :day_only), print_admin_competition_events_path(current_competition, day.id) %>
    <% end %>
  <% end %>
</p>

<% @days.each do |day| %>
  <%= render 'table', day: day %>
<% end %>

app/views/admin/events/load_day_form.html.erb
<% page_title 'Load day' %>

<% if (@from_options.size + @to_options.size) > 0 %>
  <p><b>Note:</b> Loading a day from another competition will delete all of the existing events for the day of this competition.</p>

  <%= form_tag(load_day_admin_competition_events_path) do %>
    <table class='form-table'>
      <tr>
        <td>Load from:</td>
        <td><%= select_tag 'from_day_id', options_for_select(@from_options), class: 'inline' %></td>
      </tr>
      <tr>
        <td>Save to:</td>
        <td><%= select_tag 'to_day_id', options_for_select(@to_options), class: 'inline' %></td>
      </tr>
      <tr>
        <td colspan="2"><%= submit_tag "Load", class: 'small', name: 'from[load_competition]' %></td>
      </tr>
    </table>
  <% end %>
<% else %>
  There are no themes available to load right now.
<% end %>

app/views/admin/events/new.html.erb
<% page_title 'New event' %>

<%= render 'form' %>