config/routes.rb
Rails.application.routes.draw do
  admin_domain = Cubecomp::Application.config.admin_domain

  constraints HostRouteConstraint.new(admin_domain) do
    scope module: 'admin', as: 'admin', path: (admin_domain ? "/" : "/admin"), format: false do
      root action: 'index'

      get 'login', to: 'sessions#new'
      post 'login', to: 'sessions#create'
      delete 'logout', to: 'sessions#destroy'

      resources :users, except: [:show]

      get :help, to: "help#index"

      theme_files_resources = lambda do
        member do
          get :show_image
        end

        collection do
          get :new_image
          post :create_image

          get :import_files, action: 'import_files_form'
          post :import_files
        end
      end

      resources :themes do
        resources :theme_files, except: [:show], &theme_files_resources
      end

      resources :competitions, except: [:show] do
        resources :dashboard, only: [:index]

        resources :competitors, except: [:show] do
          collection do
            get :checklist
            get :nametags
            get :email_addresses
            get :csv
            get :csv_download_active
          end

          member do
            patch :confirm
            patch :cancel
            patch :mark_as_paid
          end

          member do
            get 'email(/:activate)', to: 'competitor_email#new', as: 'new_email'
            post 'email', to: 'competitor_email#create', as: 'create_email'

            get 'email/render(.:format)(/:email_template_id)',
              to: 'competitor_email#render_template',
              as: 'render_email',
              constraints: { format: 'json' }
          end
        end

        resources :event_registrations, only: [] do
          collection do
            get :waiting
            patch :remove_all_waiting
          end
        end

        resources :events, except: [:show] do
          collection do
            get 'print/(:day_id)', action: 'print', as: "print"
            delete 'destroy_day/:day_id', action: 'destroy_day', as: 'destroy_day'

            get :import_day, action: 'import_day_form'
            post :import_day
          end

          resources :event_registrations, only: [:index, :destroy] do
            member do
              patch :update_waiting
            end
          end
        end

        resources :news, except: [:show]
        resources :theme_files, except: [:show], &theme_files_resources

        resources :email_templates, except: [:show] do
          collection do
            get :import_templates, action: 'import_templates_form'
            post :import_templates
          end
        end
      end
    end
  end

  constraints HostRouteConstraint.new(admin_domain, negate: true) do
    scope '/wca' do
      get '/autocomplete/(:q.:format)',
        to: 'wca#autocomplete',
        as: 'wca_autocomplete',
        constraints: { format: 'json' }
    end

    get '/', to: "front_page#index"

    scope '/:competition_handle' do
      post '/:locale/registration',
        to: 'competition_area/competitors#create',
        as: 'competition_area_competitor_create'

      get '/(:locale/(:theme_file))',
        to: 'competition_area#render_theme_file',
        as: 'competition_area'
    end
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < AdminController
  def index
    @financials = {}
    Competition::PRICING_MODELS.each_key do |handle|
      @financials[handle] = FinancialService.new(current_competition, PricingModel.for_handle(handle))
    end

    @counter = FinancialService.new(current_competition)

    @events_with_limits = current_competition.events.with_max_number_of_registrations.to_a
    @getting_started = getting_started

    @statistics = CompetitorStatistics.new(current_competition)
  end

  private

  def getting_started
    tips = []
    tips << :email if current_competition.email_templates.empty?
    tips << :events if current_competition.events.for_competitors_table.empty?
    tips << :theme if current_competition.theme_files.empty?
    tips << :users if current_competition.users.active.empty?
    tips += getting_started_owner_tips
    tips
  end

  def getting_started_owner_tips
    tips = []

    if current_competition.owner.blank?
      tips << :owner
    elsif current_competition.owner.address.blank?
      tips << :owner_without_address
    end

    tips
  end
end

app/views/admin/dashboard/_competitor_statistics.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Competitor statistics (guests excluded)
  </div>

  <div class="panel-body">
    <table class='default-table progress'>
      <thead>
        <tr>
          <th colspan="2">Top 10</th>
          <th>Average</th>
        </tr>
        <tr>
          <th>Oldest</th>
          <th>Youngest</th>
          <th>Age</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <% @statistics.oldest.each do |competitor| %>
              <%= competitor.name %> (<%= competitor.age %>)<br/>
            <% end %>
          </td>
          <td>
            <% @statistics.youngest.each do |competitor| %>
              <%= competitor.name %> (<%= competitor.age %>)<br/>
            <% end %>
          </td>
          <td><%= "%.1f" % @statistics.average_age %></td>
        </tr>
        <tr>
          <th>Countries</th>
          <th>Events</th>
          <th>Events</th>
        </tr>
        <tr>
          <td>
            <% @statistics.countries.each do |country, competitors| %>
              <%= country.name %> (<%= competitors.size %>)<br/>
            <% end %>
          </td>
          <td>
            <% @statistics.events.each do |competitor| %>
              <%= competitor.name %> (<%= competitor.event_registrations.size %>)<br/>
            <% end %>
          </td>
          <td><%= "%.1f" % @statistics.average_events %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/dashboard/_events_with_limits.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Events with registration limits
  </div>

  <div class="panel-body">
    <table class='default-table progress'>
      <thead>
        <tr>
          <th>Day</th>
          <th>Event</th>
          <th>Status</th>
          <th>Registrations</th>
        </tr>
      </thead>
      <tbody>
        <% @events_with_limits.each do |event| %>
          <tr>
            <td><%= l(event.day.date, format: :day_only) %></td>
            <td><%= link_to(event.name, edit_admin_competition_event_path(current_competition, event)) %></td>
            <td style="width: 300px">
              <div class="progress">
                <% progress = 100.0 * (event.number_of_confirmed_registrations.to_f / event.max_number_of_registrations.to_f) %>
                <%
                  style = if progress < 75
                    'success'
                  elsif progress >= 90
                    'danger'
                  else
                    'warning'
                  end
                %>
                <div class="progress-bar progress-bar-<%= style %>" style="width: <%= [100, progress].min %>%">
                </div>
              </div>
            </td>
            <td>
              <% link_text = "#{event.number_of_confirmed_registrations} / #{event.max_number_of_registrations}" %>
              <%= link_to(link_text, admin_competition_event_event_registrations_path(current_competition, event.id)) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/dashboard/_financial_overview.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Financial overview
  </div>

  <div class="panel-body">
    <table class='default-table financial-overview'>
      <tr>
        <th></th>
        <% current_competition.days.each do |day| %>
          <th><%= l(day.date, format: :day_only) %></th>
        <% end %>
        <th>&sum;</th>
      </tr>

      <tr>
        <th>Number of competitors</th>
        <% current_competition.days.each do |day| %>
          <td><%= @counter.competing_competitors_count(day) %></td>
        <% end %>
        <td class="line-to-the-left"><%= @counter.competing_competitors_count(*current_competition.days) %></td>
      </tr>

      <tr class="line-below">
        <th>Number of guests</th>
        <% current_competition.days.each do |day| %>
          <td><%= @counter.guest_count(day) %></td>
        <% end %>
        <td class="line-to-the-left"><%= @counter.guest_count(*current_competition.days) %></td>
      </tr>

      <% @financials.each do |pricing_model_handle, service| %>
        <tr <%= pricing_model_handle == current_competition.pricing_model ? "class=\"current-model\"".html_safe : "" %>>
          <th><%= Competition::PRICING_MODELS[pricing_model_handle] %></th>
          <% current_competition.days.each do |day| %>
            <td><%= amount = service.entrance_fee(day); amount && amount_with_currency(amount, current_competition.currency) %></td>
          <% end %>
          <td class="line-to-the-left"><%= amount_with_currency(service.entrance_fee_sum, current_competition.currency) %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/admin/dashboard/_getting_started.html.erb
<div class="panel panel-green panel-getting-started">
  <div class="panel-heading">
    Getting started
  </div>

  <div class="panel-body">
    <ul>
      <% if @getting_started.include?(:users) && current_user.policy.admin_user_menu? %>
        <li>
          <b>Users:</b>
          There are no users with permission to organize this competition.
          Please go to <%= link_to "Users", admin_users_path %> to add some.
        </li>
      <% end %>

      <% if @getting_started.include?(:owner) %>
        <li>
          <b>Owner:</b>
          You haven't specified the owner of this competition yet. Please go to
          <%= link_to "Settings", edit_admin_competition_path(current_competition) %>
          and do so.
        </li>
      <% end %>

      <% if @getting_started.include?(:owner_without_address) %>
        <li>
          <b>Owner:</b>
          The owner of this competition did not specify a personal address for the
          disclaimer page yet. Please ask him to do so.
        </li>
      <% end %>


      <% if @getting_started.include?(:events) %>
        <li>
          <b>Events:</b>
          You haven't created any events yet that competitors can register for.
          Please go to <%= link_to "Events", admin_competition_events_path(current_competition) %>
          to create or import some.
        </li>
      <% end %>

      <% if @getting_started.include?(:theme) %>
        <li>
          <b>Theme:</b>
          Your website has no theme yet. Please go to
          <%= link_to "Theme", admin_competition_theme_files_path(current_competition) %>
          to set one up.
        </li>
      <% end %>

      <% if @getting_started.include?(:email) %>
        <li>
          <b>Email:</b>
          You haven't set up any email templates yet. Please go to
          <%= link_to "Email", admin_competition_email_templates_path(current_competition) %>
          to set some up.
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/admin/dashboard/index.html.erb
<% page_title 'Dashboard' %>

<div class="dashboard">
  <% if @getting_started.present? %>
    <%= render 'getting_started' %>
  <% end %>

  <br/>

  <% if @counter.total_count > 0 %>
    <%= render 'financial_overview' %>
  <% end %>

  <% unless @events_with_limits.empty? %>
    <%= render 'events_with_limits' %>
  <% end %>

  <% if @counter.total_count >= 10 %>
    <%= render 'competitor_statistics' %>
  <% end %>
</div>