config/routes.rb
Rails.application.routes.draw do
  admin_domain = Cubecomp::Application.config.admin_domain

  constraints HostRouteConstraint.new(admin_domain) do
    scope module: 'admin', as: 'admin', path: (admin_domain ? "/" : "/admin"), format: false do
      root action: 'index'

      get 'login', to: 'sessions#new'
      post 'login', to: 'sessions#create'
      delete 'logout', to: 'sessions#destroy'

      resources :users, except: [:show]

      get :help, to: "help#index"

      theme_files_resources = lambda do
        member do
          get :show_image
        end

        collection do
          get :new_image
          post :create_image

          get :import_files, action: 'import_files_form'
          post :import_files
        end
      end

      resources :themes do
        resources :theme_files, except: [:show], &theme_files_resources
      end

      resources :competitions, except: [:show] do
        resources :dashboard, only: [:index]

        resources :competitors, except: [:show] do
          collection do
            get :checklist
            get :nametags
            get :email_addresses
            get :csv
            get :csv_download_active
          end

          member do
            patch :confirm
            patch :cancel
            patch :mark_as_paid
          end

          member do
            get 'email(/:activate)', to: 'competitor_email#new', as: 'new_email'
            post 'email', to: 'competitor_email#create', as: 'create_email'

            get 'email/render(.:format)(/:email_template_id)',
              to: 'competitor_email#render_template',
              as: 'render_email',
              constraints: { format: 'json' }
          end
        end

        resources :event_registrations, only: [] do
          collection do
            get :waiting
            patch :remove_all_waiting
          end
        end

        resources :events, except: [:show] do
          collection do
            get 'print/(:day_id)', action: 'print', as: "print"
            delete 'destroy_day/:day_id', action: 'destroy_day', as: 'destroy_day'

            get :import_day, action: 'import_day_form'
            post :import_day
          end

          resources :event_registrations, only: [:index, :destroy] do
            member do
              patch :update_waiting
            end
          end
        end

        resources :news, except: [:show]
        resources :theme_files, except: [:show], &theme_files_resources

        resources :email_templates, except: [:show] do
          collection do
            get :import_templates, action: 'import_templates_form'
            post :import_templates
          end
        end
      end
    end
  end

  constraints HostRouteConstraint.new(admin_domain, negate: true) do
    scope '/wca' do
      get '/autocomplete/(:q.:format)',
        to: 'wca#autocomplete',
        as: 'wca_autocomplete',
        constraints: { format: 'json' }
    end

    get '/', to: "front_page#index"

    scope '/:competition_handle' do
      post '/:locale/registration',
        to: 'competition_area/competitors#create',
        as: 'competition_area_competitor_create'

      get '/(:locale/(:theme_file))',
        to: 'competition_area#render_theme_file',
        as: 'competition_area'
    end
  end
end

app/models/competitor_email.rb
class CompetitorEmail
  include ActiveModel::Validations
  include ActiveModel::Model

  attr_accessor :from_name, :from_email, :to_name, :to_email, :cc_name, :cc_email, :subject, :content

  validates :from_name, presence: true
  validates :to_name, presence: true

  validates :from_email, presence: true
  validates :from_email, email: true, allow_nil: true, allow_blank: true

  validates :to_email, presence: true
  validates :to_email, email: true, allow_nil: true, allow_blank: true

  validates :subject, presence: true
  validates :content, presence: true

  def self.for_competitor(competitor)
    competition = competitor.competition

    attributes = {
      from_name: competition.staff_name || competition.name,
      from_email: competition.staff_email,
      to_name: competitor.name,
      to_email: competitor.email,
    }

    if competition.cc_staff?
      attributes[:cc_name] = competition.staff_name
      attributes[:cc_email] = competition.staff_email
    end

    new(attributes)
  end
end

app/controllers/admin/competitor_email_controller.rb
class Admin::CompetitorEmailController < AdminController
  before_action :set_competitor_and_email

  def new
  end

  def create
    @email.subject = email_params[:subject]
    @email.content = email_params[:content]

    unless @email.valid?
      render :new
      return
    end

    success = if @activate
      activate_competitor
    else
      true
    end

    send_email if success
    redirect_to admin_competition_competitors_path(current_competition), flash: flashes(@activate, success)
  end

  def render_template
    template = current_competition.email_templates.find(params[:email_template_id])
    renderer = EmailTemplateRenderer.new(template, @competitor, current_user)
    respond_to do |format|
      format.json do
        render json: {
          subject: renderer.render_subject,
          content: renderer.render_content
        }
      end
    end
  end

  private

  def email_params
    params.require(:competitor_email).permit(:subject, :content)
  end

  def set_competitor_and_email
    @competitor = current_competition.competitors.find(params[:id])
    @email = CompetitorEmail.for_competitor(@competitor)
    @activate = params[:activate]
  end

  def activate_competitor
    @competitor.state = 'confirmed'
    @competitor.confirmation_email_sent = true
    @competitor.save
  end

  def send_email
    CompetitorMailer.competitor_email(@email).deliver_now
  end

  def flashes(activate, success)
    if activate && success
      { notice: "Email to #{@email.to_email} sent and competitor successfully confirmed." }
    elsif activate && !success
      { error: "Failed to confirm competitor." }
    else
      { notice: "Email to #{@email.to_email} sent." }
    end
  end
end

app/views/admin/competitor_email/new.html.erb
<script type='text/javascript'>
  var templateFetcher = new EmailTemplateFetcher('<%= j(render_email_admin_competition_competitor_path(current_competition, @competitor, format: :json)) %>')
</script>

<% if @activate %>
  <% page_title "Confirmation email for #{@competitor.name}" %>
<% else %>
  <% page_title "Email for #{@competitor.name}" %>
<% end %>

<%= form_for(@email, url: create_email_admin_competition_competitor_path(current_competition, @competitor)) do |f| %>
  <%= render 'form_errors', object: @email, label: 'email' %>

  <% if current_competition.email_templates.exists? %>
    <%= form_section 'Template' do %>
      <table class="form-table">
        <tr>
          <td><label>Template:</label></td>
          <td>
            <select onchange="templateFetcher.fetch(this.value)">
              <option></option>
              <%=
                options_for_select(current_competition.email_templates.map{ |template|
                  [ template.name, template.id ]
                })
              %>
            </select>
          </td>
        </tr>
      </table>
    <% end %>
  <% end %>

  <%= form_section 'Settings' do %>
    <table class="form-table">
      <tr>
        <td><label>From:</label></td>
        <td><%= @email.from_name %> (<%= @email.from_email %>)</td>
      </tr>
      <tr>
        <td><label>To:</label></td>
        <td><%= @email.to_name %> (<%= @email.to_email %>)</td>
      </tr>
      <% if @email.cc_email %>
        <tr>
          <td><%= f.label :cc_email, 'CC:' %></td>
          <td><%= @email.cc_name %> (<%= @email.cc_email %>)</td>
        </tr>
      <% end %>
      <tr>
        <td><%= f.label :subject %></td>
        <td><%= f.text_field :subject %></td>
      </tr>
    </table>
  <% end %>

  <%= form_section 'Text' do %>
    <%= text_editor(f, :content, { lineWrapping: true }) %>
    <script>
      templateFetcher.setEditor(textEditor);
    </script>
  <% end %>

  <%= form_section 'Competitor' do %>
    <table class="form-table">
      <tr>
        <td><label>Birthday:</label></td>
        <td><%= @competitor.birthday %> (<%= @competitor.age %>)</td>
      </tr>
      <tr>
        <td><label>WCA ID:</label></td>
        <td><%= @competitor.wca %></td>
      </tr>
      <tr>
        <td><label>Country:</label></td>
        <td><%= @competitor.country.name %> <% if @competitor.local %>(<%= current_competition.city_name %>)<% end %></td>
      </tr>
      <tr>
        <td><label>Gender:</label></td>
        <td><%= @competitor.gender %></td>
      </tr>
      <tr>
        <td><label>Comment:</label></td>
        <td><%= @competitor.user_comment %></td>
      </tr>
      <tr>
        <td><label>Events:</label></td>
        <td>
          <% counts = @competitor.event_registration_counts(true) %>
          <%=
            tooltip(
              "#{counts.join("+")}=#{counts.reduce(:+)}",
              events_by_day_list(@competitor)
            )
          %>
        </td>
      </tr>
    </table>
  <% end %>

  <% if @activate %>
    <input type="hidden" name="activate" value="1" />
    <%= submit_button(f, 'Send email and confirm competitor') %>
  <% else %>
    <%= submit_button(f, 'Send email') %>
  <% end %>

  <%= back_button(admin_competition_competitors_path) %>
<% end %>