config/routes.rb
Rails.application.routes.draw do
  admin_domain = Cubecomp::Application.config.admin_domain

  constraints HostRouteConstraint.new(admin_domain) do
    scope module: 'admin', as: 'admin', path: (admin_domain ? "/" : "/admin"), format: false do
      root action: 'index'

      get 'login', to: 'sessions#new'
      post 'login', to: 'sessions#create'
      delete 'logout', to: 'sessions#destroy'

      resources :users, except: [:show]

      get :help, to: "help#index"

      theme_files_resources = lambda do
        member do
          get :show_image
        end

        collection do
          get :new_image
          post :create_image

          get :import_files, action: 'import_files_form'
          post :import_files
        end
      end

      resources :themes do
        resources :theme_files, except: [:show], &theme_files_resources
      end

      resources :competitions, except: [:show] do
        resources :dashboard, only: [:index]

        resources :competitors, except: [:show] do
          collection do
            get :checklist
            get :nametags
            get :email_addresses
            get :csv
            get :csv_download_active
          end

          member do
            patch :confirm
            patch :cancel
            patch :mark_as_paid
          end

          member do
            get 'email(/:activate)', to: 'competitor_email#new', as: 'new_email'
            post 'email', to: 'competitor_email#create', as: 'create_email'

            get 'email/render(.:format)(/:email_template_id)',
              to: 'competitor_email#render_template',
              as: 'render_email',
              constraints: { format: 'json' }
          end
        end

        resources :event_registrations, only: [] do
          collection do
            get :waiting
            patch :remove_all_waiting
          end
        end

        resources :events, except: [:show] do
          collection do
            get 'print/(:day_id)', action: 'print', as: "print"
            delete 'destroy_day/:day_id', action: 'destroy_day', as: 'destroy_day'

            get :import_day, action: 'import_day_form'
            post :import_day
          end

          resources :event_registrations, only: [:index, :destroy] do
            member do
              patch :update_waiting
            end
          end
        end

        resources :news, except: [:show]
        resources :theme_files, except: [:show], &theme_files_resources

        resources :email_templates, except: [:show] do
          collection do
            get :import_templates, action: 'import_templates_form'
            post :import_templates
          end
        end
      end
    end
  end

  constraints HostRouteConstraint.new(admin_domain, negate: true) do
    scope '/wca' do
      get '/autocomplete/(:q.:format)',
        to: 'wca#autocomplete',
        as: 'wca_autocomplete',
        constraints: { format: 'json' }
    end

    get '/', to: "front_page#index"

    scope '/:competition_handle' do
      post '/:locale/registration',
        to: 'competition_area/competitors#create',
        as: 'competition_area_competitor_create'

      get '/(:locale/(:theme_file))',
        to: 'competition_area#render_theme_file',
        as: 'competition_area'
    end
  end
end

app/models/theme.rb
class Theme < ActiveRecord::Base
  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: true }, allow_nil: true, allow_blank: true

  auto_strip_attributes :name

  has_many :files, class_name: 'ThemeFile', dependent: :destroy, autosave: true
end

app/controllers/admin/themes_controller.rb
class Admin::ThemesController < AdminController
  before_action :set_theme, only: [:show, :edit, :update, :destroy]
  before_action :ensure_user_can_see_admin_menu
  skip_before_action :ensure_current_competition

  def index
    @themes = Theme.all
  end

  def new
    @theme = Theme.new
  end

  def show
  end

  def edit
  end

  def create
    @theme = Theme.new(theme_params)

    if @theme.save
      redirect_to admin_themes_path
    else
      render :new
    end
  end

  def update
    if @theme.update(theme_params)
      redirect_to admin_themes_path, notice: 'Theme was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @theme.destroy
    redirect_to admin_themes_path, notice: 'Theme was successfully deleted.'
  end

  private

  def set_theme
    @theme = Theme.find(params[:id])
  end

  def theme_params
    params.require(:theme).permit(:name)
  end
end

app/views/admin/themes/_form.html.erb
<%= form_for([:admin, @theme]) do |f| %>
  <%= render 'form_errors', object: @theme, label: 'theme' %>

  <%= form_section 'Settings' do %>
    <table class="form-table">
      <tr>
        <td><%= f.label :name, 'Name:' %></td>
        <td><%= f.text_field :name %></td>
      </tr>
    </table>
  <% end %>

  <%= submit_button(f) %>
  <%= back_button(admin_themes_path) %>
<% end %>

app/views/admin/themes/edit.html.erb
<% page_title @theme.name %>

<%= render 'form' %>

app/views/admin/themes/index.html.erb
<% page_title 'Themes' %>

<p><%= link_to 'New theme', new_admin_theme_path %></p>

<table class='default-table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Files</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @themes.each do |theme| %>
      <tr>
        <td><%= link_to theme.name, admin_theme_theme_files_path(theme) %></td>
        <td><%= theme.files.count %></td>
        <td class='actions'>
          <%= edit_button(edit_admin_theme_path(theme)) %>
          <%= delete_button(admin_theme_path(theme), method: :delete, data: { confirm: 'Are you sure?' }) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/themes/new.html.erb
<% page_title 'New theme' %>

<%= render 'form' %>

app/views/admin/themes/show.html.erb
<% page_title @theme.name %>

<%= link_to 'New template', new_admin_theme_theme_file_path(@theme) %>

<ul>
  <% @theme.files.each do |template| %>
    <li>
      <%= link_to template.filename, edit_admin_theme_file_path(template) %>
      (<%= link_to 'Destroy', admin_theme_file_path(template), method: :delete, data: { confirm: 'Are you sure?' } %>)
    </li>
  <% end %>
</ul>